# Generated by Django 2.2 on 2020-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='ggd guuuyuy hggg gggds gggdg'),
            preserve_default=False,
        ),
    ]
