# Generated by Django 2.2 on 2020-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='fuel_type',
            field=models.CharField(choices=[('D', 'Diesel'), ('P', 'Petrol'), ('D', 'Hybrid'), ('G', 'Petroleum Gas')], max_length=2),
        ),
    ]
