# Generated by Django 2.2 on 2020-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200112_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Petroleum Gas', 'Petroleum Gas')], max_length=15),
        ),
    ]
